# Generated by Django 3.0.5 on 2021-05-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='emenites',
            field=models.ManyToManyField(to='App.Emenities'),
        ),
    ]
