# Generated by Django 3.0.5 on 2021-05-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_hotels_emenites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='hotel_price',
            new_name='price',
        ),
    ]
