# Generated by Django 3.0.5 on 2021-05-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210506_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='emenites',
            new_name='emenities',
        ),
    ]
